from a_protocol_0.enums.AbstractEnum import AbstractEnum


class CommandEnum(AbstractEnum):
    IS_PLUGIN_WINDOW_VISIBLE = "IS_PLUGIN_WINDOW_VISIBLE"
    SEARCH_SET = "SEARCH_SET"
    SYNC_PRESETS = "SYNC_PRESETS"
    SHOW_PLUGINS = "SHOW_PLUGINS"
    SETUP_HOTKEYS = "SETUP_HOTKEYS"
    SHOW_HIDE_PLUGINS = "SHOW_HIDE_PLUGINS"
    HIDE_PLUGINS = "HIDE_PLUGINS"
    ARROW_UP = "ARROW_UP"
