components:
  schemas:
    toto: {}
info:
  description: Protocol0 internal remote script API
  title: P0 Internal API
  version: 1.0.0
openapi: 3.0.2
paths:
  /test:
    get:
      responses:
        '200':
          description: ''
