from protocol0.shared.AbstractEnum import AbstractEnum


class SongDataEnum(AbstractEnum):
    SELECTED_RECORDING_BAR_LENGTH = "SELECTED_RECORDING_BAR_LENGTH"
    SELECTED_DUPLICATE_SCENE_BAR_LENGTH = "SELECTED_DUPLICATE_SCENE_BAR_LENGTH"
    SELECTED_SCENE_INDEX = "SELECTED_SCENE"
    SELECTED_TRACK_INDEX = "SELECTED_TRACK_INDEX"
    LAST_MANUALLY_STARTED_SCENE_INDEX = "LAST_MANUALLY_STARTED_SCENE_INDEX"
    LAST_MANUALLY_STARTED_SCENE_BAR_POSITION = "LAST_MANUALLY_STARTED_SCENE_BAR_POSITION"
