from protocol0.shared.AbstractEnum import AbstractEnum


class SongDataEnum(AbstractEnum):
    SELECTED_SCENE_INDEX = "SELECTED_SCENE_INDEX"
    SELECTED_SCENE_POSITION = "SELECTED_SCENE_POSITION"
    SELECTED_TRACK_INDEX = "SELECTED_TRACK_INDEX"
