from protocol0.shared.AbstractEnum import AbstractEnum


class SongDataEnum(AbstractEnum):
    SCENE_RECORDING_BAR_LENGTH = "SCENE_RECORDING_BAR_LENGTH"
    SCENE_CROP_BAR_LENGTH = "SCENE_CROP_BAR_LENGTH"
    SELECTED_SCENE_INDEX = "SELECTED_SCENE_INDEX"
    SELECTED_TRACK_INDEX = "SELECTED_TRACK_INDEX"
    LAST_MANUALLY_STARTED_SCENE_INDEX = "LAST_MANUALLY_STARTED_SCENE_INDEX"
    LAST_MANUALLY_STARTED_SCENE_BAR_POSITION = "LAST_MANUALLY_STARTED_SCENE_BAR_POSITION"
